# Generated by Django 3.2.7 on 2021-10-14 07:58

from django.db import migrations, models
import django.db.models.deletion
import resumes_vacancies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=90, verbose_name='Напрям роботи')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.CharField(max_length=90, verbose_name='Бажаний вид діяльності')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=45, verbose_name='Назва компанії')),
                ('company_short_description', models.TextField(blank=True, verbose_name='Короткий опис компанії (якщо ви з нами вже знайомі, то можете лишити поле пустим)')),
                ('vacancy_name', models.CharField(max_length=45, verbose_name='Назва вакансії')),
                ('vacancy_description', models.TextField(verbose_name="Опис вакансії та обов'язки")),
                ('vacancy_requirements', models.TextField(verbose_name='Вимоги до кандидата')),
                ('vacancy_working_conditions', models.TextField(verbose_name='Умови праці')),
                ('vacancy_salary', models.CharField(max_length=20, verbose_name='Грошова винагорода')),
                ('vacancy_benefits', models.TextField(verbose_name='Переваги')),
                ('vacancy_contacts', models.TextField(verbose_name='Контакти')),
                ('company_website', models.TextField(blank=True, verbose_name='Посилання на сайт компанії')),
                ('vacancy_date_added', models.DateTimeField(auto_now=True)),
                ('company_direction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='resumes_vacancies.directionsmodel')),
            ],
            options={
                'ordering': ['vacancy_date_added'],
            },
        ),
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_pib', models.CharField(max_length=90, verbose_name='П.І.Б.')),
                ('students_phone_number', models.CharField(max_length=50, verbose_name='Номер телефону')),
                ('students_email', models.CharField(max_length=90, verbose_name='Електронна пошта')),
                ('students_work_time', models.TextField(verbose_name='Бажаний вид діяльності')),
                ('students_resume_file', models.FileField(blank=True, null=True, upload_to=resumes_vacancies.models.ResumeModel.upload_to_user, verbose_name='Резюме (PDF)')),
                ('students_resume_link', models.TextField(blank=True, null=True, verbose_name='Посилання на портфолія')),
                ('resume_date_added', models.DateTimeField(auto_now=True)),
                ('students_direction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='resumes_vacancies.directionsmodel')),
            ],
        ),
    ]
