# Generated by Django 3.2.7 on 2021-10-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=45, verbose_name='Напрям роботи')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=45, verbose_name='Назва компанії')),
                ('company_short_description', models.TextField(blank=True, verbose_name='Короткий опис компанії (якщо ви з нами вже знайомі, то можете лишити поле пустим)')),
                ('vacancy_name', models.CharField(max_length=45, verbose_name='Назва вакансії')),
                ('vacancy_description', models.TextField(verbose_name="Опис вакансії та обов'язки")),
                ('vacancy_requirements', models.TextField(verbose_name='Вимоги до кандидата')),
                ('vacancy_working_conditions', models.TextField(verbose_name='Умови праці')),
                ('vacancy_salary', models.CharField(max_length=20, verbose_name='Грошова винагорода')),
                ('vacancy_benefits', models.TextField(verbose_name='Переваги')),
                ('vacancy_contacts', models.TextField(verbose_name='Контакти')),
                ('company_website', models.SlugField(blank=True, verbose_name='Посилання на сайт компанії')),
                ('company_direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes_vacancies.directionsmodel')),
            ],
        ),
    ]
