# Generated by Django 3.2.7 on 2021-10-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionsmodel',
            name='direction',
            field=models.CharField(max_length=90, verbose_name='Напрям роботи'),
        ),
    ]
