# Generated by Django 3.2.7 on 2021-10-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_vacancies', '0002_alter_directionsmodel_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancymodel',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='vacancymodel',
            name='vacancy_date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
