# Generated by Django 3.2.7 on 2021-10-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_vacancies', '0003_auto_20211004_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancymodel',
            options={'ordering': ['vacancy_date_added']},
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='company_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes_vacancies.directionsmodel'),
        ),
    ]
