# Generated by Django 3.2.7 on 2021-10-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_vacancies', '0004_auto_20211004_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancymodel',
            name='company_website',
            field=models.URLField(blank=True, verbose_name='Посилання на сайт компанії'),
        ),
    ]
