# Generated by Django 3.2.7 on 2021-10-13 20:17

from django.db import migrations, models
import django.db.models.deletion
import resumes_vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_vacancies', '0005_alter_vacancymodel_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.CharField(max_length=90, verbose_name='Бажаний вид діяльності')),
            ],
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='company_direction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='resumes_vacancies.directionsmodel'),
        ),
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_pib', models.CharField(max_length=90, verbose_name='П.І.Б.')),
                ('students_phone_number', models.CharField(max_length=50, verbose_name='Номер телефону')),
                ('students_email', models.CharField(max_length=90, verbose_name='Електронна пошта')),
                ('students_resume_file', models.FileField(blank=True, null=True, upload_to=resumes_vacancies.models.ResumeModel.upload_to_user, verbose_name='Резюме (PDF)')),
                ('students_resume_link', models.TextField(blank=True, null=True, verbose_name='Посилання на портфолія')),
                ('resume_date_added', models.DateTimeField(auto_now=True)),
                ('students_direction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='resumes_vacancies.directionsmodel')),
                ('students_work_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resumes_vacancies.worktimemodel')),
            ],
        ),
    ]
