# Generated by Django 3.2.7 on 2021-10-13 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_vacancies', '0006_auto_20211013_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='students_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes_vacancies.directionsmodel'),
        ),
        migrations.RemoveField(
            model_name='resumemodel',
            name='students_work_time',
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='students_work_time',
            field=models.ManyToManyField(to='resumes_vacancies.WorkTimeModel'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='company_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes_vacancies.directionsmodel'),
        ),
    ]
