# Generated by Django 3.2.7 on 2021-10-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_vacancies', '0008_alter_vacancymodel_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='students_work_time',
            field=models.ManyToManyField(related_name='work_time_list', to='resumes_vacancies.WorkTimeModel'),
        ),
    ]
