# Generated by Django 3.2.7 on 2021-10-13 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_vacancies', '0009_alter_resumemodel_students_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='students_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='resumes_vacancies.directionsmodel'),
        ),
        migrations.AlterField(
            model_name='vacancymodel',
            name='company_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='resumes_vacancies.directionsmodel'),
        ),
    ]
